namespace Nook.SourceGenerators.Tests.TestCases;

internal static class MinimalStore
{
    public const string Input = """
        using Nook.Core;

        namespace MinimalStoreTest
        {
            public record MyState(int Counter)
            {
                public MyState() : this(0) { }
            }

            public class MinimalStore : Store<MyState>
            {
                // Nothing
            }
        }
        """;

    public const string ExpectedOutput = """
        // <auto-generated/>
        #nullable enable
        
        namespace MinimalStoreTest;
        
        static partial class UseMinimalStoreNookExtensions
        {
            public static global::MinimalStoreTest.MyState GetState(this global::Nook.Core.IUse<global::MinimalStoreTest.MinimalStore> value)
            {
                return ((global::Nook.Core.Use<global::MinimalStoreTest.MinimalStore>)value).Instance.CurrentState;
            }
        }

        """;
}